#!/usr/bin/env bash
set -euo pipefail

PROTO_DIR="$(dirname "$0")/../protos"
OUT_DIR="$(dirname "$0")/../app/grpc_server/generated"

mkdir -p "$OUT_DIR"
touch "$OUT_DIR/__init__.py"

python -m grpc_tools.protoc \
  -I"$PROTO_DIR" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$PROTO_DIR"/*.proto

# Fix relative imports generated by grpc_tools
for f in "$OUT_DIR"/*_pb2_grpc.py; do
  sed -i 's/^import \(.*_pb2\)/from . import \1/' "$f"
done

echo "Protos compiled → $OUT_DIR"
